name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 1.999.1
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: stripe_android
      ios:
        default_package: stripe_ios

dependencies:
  flutter:
    sdk: flutter
  stripe_ios: ^9.0.0
  stripe_android:
    git:
      ref: 1.999.1
      url: https://github.com/StoneNan/flutter_stripe.git
      path: packages/stripe_android
  stripe_platform_interface: 
    git:
      ref: 9.0.1
      url: https://github.com/StoneNan/flutter_stripe.git
      path: packages/stripe_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
